version: "3.8"

services:
  app:
    build: .
    depends_on:
      - db
    networks:
      - backend
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src
      - /usr/src/node_modules
    command: npm run start

  db:
    image: mysql:5.7
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=rates
    restart: always
    expose:
      - "3306"
    ports:
      - '2401:3306'
    healthcheck:
      test: mysqladmin -p$$MYSQL_ROOT_PASSWORD ping -h 127.0.0.1
      interval: 5s
      timeout: 5s
      retries: 3
    
  test-db:
    image: mysql:5.7
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=rates
    restart: always
    expose:
      - "3306"
    ports:
      - '2401:3306'
    healthcheck:
      test: mysqladmin -p$$MYSQL_ROOT_PASSWORD ping -h 127.0.0.1
      interval: 5s
      timeout: 5s
      retries: 3

networks:
  backend:
    name: nestjsnetwork
